# -*- coding: utf-8 -*-
"""RL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f5KTD4WLv3UGxIi_OxoGO_t-OQP4_9Vk
"""

import torch
import torch.nn as nn
import torch.optim as optim
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
from sentence_transformers import SentenceTransformer
import random
import re

"""RL policy on GSM8K dataset"""

import torch
import torch.nn as nn
import torch.optim as optim
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from sentence_transformers import SentenceTransformer
import random
import re

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

dataset = load_dataset("gsm8k", "main", split="train[:300]")
dataset_test = load_dataset("gsm8k", "main", split="test[:100]")

model_name = "google/flan-t5-large"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name).to(device)
model.eval()

#LLM call
def call_llm(question, prev_answer=None):
    if prev_answer:
        prompt = f"""
        Question: {question}
        Previous answer: {prev_answer}
        The previous solution may be incorrect.
        Re-solve carefully step by step and give the final answer after '####'.
        """
    else:
        prompt = f"""
        Question: {question}
        Let's think step by step.
        """

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        padding=True
    ).to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=128,
            do_sample=False,
            temperature=0.0
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return response

#numerical extraction

def extract_gsm8k_answer(text):
    if "####" in text:
        return text.split("####")[-1].strip()
    nums = re.findall(r"-?\d+\.?\d*", text)
    return nums[-1] if nums else None

def extract_number(text):
    nums = re.findall(r"-?\d+\.?\d*", text)
    return nums[-1] if nums else None

#embed model

embed_model = SentenceTransformer("all-MiniLM-L6-v2")

#set environment
class SelfCorrectionEnv:
    def __init__(self, dataset, max_revisions=3):
        self.dataset = dataset
        self.max_revisions = max_revisions

    def reset(self):
        self.sample = random.choice(self.dataset)
        self.question = self.sample["question"]
        self.solution = self.sample["answer"]
        self.answer = None
        self.revisions = 0
        return self.get_state()

    def get_state(self):
        text = self.question
        if self.answer:
            text += " " + self.answer

        embedding = embed_model.encode(text)
        state = torch.tensor(embedding, dtype=torch.float32)
        revision_tensor = torch.tensor([self.revisions], dtype=torch.float32)

        return torch.cat([state, revision_tensor])

    def step(self, action):
        done = False

        # Action 0 = STOP
        if action == 0 or self.revisions >= self.max_revisions:
            done = True
            pred = extract_number(self.answer) if self.answer else None
            true = extract_number(self.solution)
            reward = 1 if pred == true else 0
            return self.get_state(), reward, done

        # Action 1 = REVISE
        self.answer = call_llm(self.question, self.answer)
        self.revisions += 1
        reward = -0.05  # small cost for revision

        return self.get_state(), reward, done

class PolicyNet(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.ReLU(),
            nn.Linear(256, 2),
            nn.Softmax(dim=-1)
        )

    def forward(self, x):
      probs = self.net(x)
      probs = torch.clamp(probs, min=1e-8, max=1.0)
      probs = probs / probs.sum()
      return probs

def train(env, policy, episodes=200):
    optimizer = optim.Adam(policy.parameters(), lr=5e-5)
    gamma = 0.99

    for ep in range(episodes):
        state = env.reset()
        log_probs = []
        rewards = []
        done = False

        while not done:
            state = state.to(device)
            probs = policy(state)
            dist = torch.distributions.Categorical(probs)
            action = dist.sample()

            log_probs.append(dist.log_prob(action))
            next_state, reward, done = env.step(action.item())
            rewards.append(reward)
            state = next_state

        # Discount rewards
        G = 0
        returns = []
        for r in reversed(rewards):
            G = r + gamma * G
            returns.insert(0, G)

        returns = torch.tensor(returns).to(device)

        if len(returns) > 1:
          returns = (returns - returns.mean()) / (returns.std() + 1e-8)

        loss = 0
        for log_prob, R in zip(log_probs, returns):
            loss -= log_prob * R

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if ep % 10 == 0:
            print(f"Episode {ep} | Total Reward: {sum(rewards):.2f}")

env = SelfCorrectionEnv(dataset)
input_dim = env.reset().shape[0]

policy = PolicyNet(input_dim).to(device)

train(env, policy, episodes=100)

sample = dataset[0]

print("QUESTION:")
print(sample["question"])

response = call_llm(sample["question"])

print("\nMODEL OUTPUT:")
print(response)

print("\nTRUE ANSWER:")
print(sample["answer"])

# Cell 1 — download raw files with wget (bypasses HF client timeout)
!wget -q "https://huggingface.co/datasets/openai/gsm8k/resolve/main/main/train-00000-of-00001.parquet" -O gsm8k_train.parquet
!wget -q "https://huggingface.co/datasets/openai/gsm8k/resolve/main/main/test-00000-of-00001.parquet"  -O gsm8k_test.parquet

# Cell 2 — load from local files
import pandas as pd
from datasets import Dataset

df_train = pd.read_parquet("gsm8k_train.parquet").head(300)
df_test  = pd.read_parquet("gsm8k_test.parquet").head(100)

dataset      = Dataset.from_pandas(df_train)
dataset_test = Dataset.from_pandas(df_test)

print(dataset[0])   # verify it loaded

"""RL policy on Synthetic dataset

"""

"""
RL-based Self-Correction for Math Reasoning (Synthetic Simple Dataset)
"""

import torch
import torch.nn as nn
import torch.optim as optim
from sentence_transformers import SentenceTransformer
import random
import re

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

def generate_synthetic_dataset(n: int = 300) -> list[dict]:
    """Single-digit arithmetic; answer in GSM8K '#### N' format."""
    ops = {
        "+": lambda a, b: a + b,
        "-": lambda a, b: a - b,
        "*": lambda a, b: a * b,
    }
    samples = []
    for _ in range(n):
        op_sym = random.choice(list(ops.keys()))
        a = random.randint(1, 9)
        b = random.randint(1, 9)
        if op_sym == "-" and b > a:
            a, b = b, a
        result   = ops[op_sym](a, b)
        question = f"What is {a} {op_sym} {b}?"
        answer   = f"The answer is {result}. #### {result}"
        samples.append({"question": question, "answer": answer})
    return samples


random.seed(42)
dataset      = generate_synthetic_dataset(300)
dataset_test = generate_synthetic_dataset(100)
print(f"Synthetic train: {len(dataset)}  |  test: {len(dataset_test)}")
print("Example:", dataset[0])

def extract_gsm8k_answer(text: str) -> str | None:
    if "####" in text:
        return text.split("####")[-1].strip().replace(",", "")
    nums = re.findall(r"-?\d+\.?\d*", text)
    return nums[-1] if nums else None


def extract_number(text: str) -> str | None:
    if text is None:
        return None
    if "####" in text:
        return text.split("####")[-1].strip().replace(",", "")
    nums = re.findall(r"-?\d[\d,]*\.?\d*", text)
    return nums[-1].replace(",", "") if nums else None


def answers_match(pred: str | None, true: str | None) -> bool:
    if pred is None or true is None:
        return False
    try:
        return abs(float(pred) - float(true)) < 1e-3
    except ValueError:
        return pred.strip() == true.strip()

class SimulatedSolver:
    """
    Mimics an imperfect LLM with realistic and learnable correction behaviour.

    Parameters
    ----------
    initial_accuracy : float  – P(correct) on first call
    correction_rate  : float  – P(wrong -> correct) on revision
    degradation_rate : float  – P(correct -> wrong) on revision
    """

    def __init__(
        self,
        initial_accuracy: float = 0.70,
        correction_rate:  float = 0.75,
        degradation_rate: float = 0.04,
    ):
        self.initial_accuracy = initial_accuracy
        self.correction_rate  = correction_rate
        self.degradation_rate = degradation_rate
        self._true_cache: dict[str, float] = {}

    def _true_value(self, question: str) -> float:
        if question in self._true_cache:
            return self._true_cache[question]
        m = re.match(r"What is (\d+) ([+\-*]) (\d+)\?", question)
        result = eval(f"{m.group(1)}{m.group(2)}{m.group(3)}") if m else 0
        self._true_cache[question] = float(result)
        return float(result)

    def _wrong_answer(self, true_val: float) -> float:
        delta = random.choice([-3, -2, -1, 1, 2, 3])
        wrong = true_val + delta
        if abs(wrong - true_val) < 1e-3:
            wrong += 1
        return wrong

    def __call__(self, question: str, prev_answer: str | None = None) -> str:
        true_val = self._true_value(question)

        if prev_answer is None:
            value = (true_val if random.random() < self.initial_accuracy
                     else self._wrong_answer(true_val))
        else:
            prev_num     = extract_number(prev_answer)
            prev_correct = answers_match(prev_num, str(true_val))
            if prev_correct:
                value = (self._wrong_answer(true_val)
                         if random.random() < self.degradation_rate
                         else true_val)
            else:
                value = (true_val if random.random() < self.correction_rate
                         else self._wrong_answer(true_val))

        int_val = int(round(value))
        return f"The answer is {int_val}. #### {int_val}"


solver = SimulatedSolver(
    initial_accuracy=0.70,
    correction_rate=0.75,
    degradation_rate=0.04,
)

def call_llm(question: str, prev_answer: str | None = None) -> str:
    return solver(question, prev_answer)

embed_model = SentenceTransformer("all-MiniLM-L6-v2")
EMBED_DIM   = embed_model.get_sentence_embedding_dimension()   # 384

class SelfCorrectionEnv:
    """
    State  : sentence embedding of (question + current answer) + normalised
             revision count
    Actions: 0 = STOP  |  1 = REVISE
"""

    def __init__(self, dataset, max_revisions: int = 3):
        self.dataset       = dataset
        self.max_revisions = max_revisions

    def reset(self):
        self.sample    = random.choice(self.dataset)
        self.question  = self.sample["question"]
        self.solution  = self.sample["answer"]
        self.true_ans  = extract_gsm8k_answer(self.solution)
        self.revisions = 0
        self.answer    = call_llm(self.question)
        return self._get_state()

    def _get_state(self) -> torch.Tensor:
        text      = self.question + " " + (self.answer or "")
        embedding = embed_model.encode(text)
        state     = torch.tensor(embedding, dtype=torch.float32)
        rev_feat  = torch.tensor(
            [self.revisions / self.max_revisions], dtype=torch.float32
        )
        return torch.cat([state, rev_feat])

    def step(self, action: int):
        done = False

        if action == 0 or self.revisions >= self.max_revisions:
            done    = True
            correct = answers_match(extract_number(self.answer), self.true_ans)
            reward  = 1.0 if correct else -0.30      # ← changed from +0.05
            return self._get_state(), reward, done

        prev_correct   = answers_match(extract_number(self.answer), self.true_ans)
        self.answer    = call_llm(self.question, self.answer)
        self.revisions += 1
        new_correct    = answers_match(extract_number(self.answer), self.true_ans)

        if   new_correct and not prev_correct:  reward = +0.80
        elif prev_correct and not new_correct:  reward = -0.50  # ← was -0.10
        elif prev_correct and new_correct:      reward = +0.10
        else:                                   reward = -0.05  # ← was +0.00

        return self._get_state(), reward, done

class PolicyNet(nn.Module):
    def __init__(self, input_dim: int):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Linear(128, 2),
            nn.Softmax(dim=-1),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        probs = self.net(x)
        probs = torch.clamp(probs, min=1e-8)
        return probs / probs.sum()


def train(
    env: SelfCorrectionEnv,
    policy: PolicyNet,
    episodes: int = 600,
    entropy_coef: float = 0.01,
    baseline_decay: float = 0.95,
) -> list[float]:
    """
    Improvements over vanilla REINFORCE
    ------------------------------------
    baseline     : exponential moving average of episode returns, subtracted
                   from each return before computing the loss.  Reduces variance
                   without introducing bias (unlike a learned value function).
    entropy_coef : adds β·H(π) to the objective, encouraging exploration early
                   in training and preventing premature policy collapse.
    """
    optimizer  = optim.Adam(policy.parameters(), lr=1e-3)
    gamma      = 0.99
    reward_log = []
    baseline   = 0.0   # running EMA of episode return

    for ep in range(episodes):
        state     = env.reset()
        log_probs = []
        entropies = []
        rewards   = []
        done      = False

        while not done:
            state = state.to(device)
            probs = policy(state)
            dist  = torch.distributions.Categorical(probs)
            action = dist.sample()

            log_probs.append(dist.log_prob(action))
            entropies.append(dist.entropy())

            next_state, reward, done = env.step(action.item())
            rewards.append(reward)
            state = next_state

        # Discounted returns
        G       = 0.0
        returns = []
        for r in reversed(rewards):
            G = r + gamma * G
            returns.insert(0, G)

        ep_return = returns[0]
        baseline  = baseline_decay * baseline + (1 - baseline_decay) * ep_return

        returns_t = torch.tensor(returns, dtype=torch.float32).to(device)
        # Subtract running baseline
        returns_t = returns_t - baseline
        if len(returns_t) > 1:
            returns_t = returns_t / (returns_t.std() + 1e-8)

        policy_loss  = torch.stack(
            [-lp * R for lp, R in zip(log_probs, returns_t)]
        ).sum()
        entropy_loss = -entropy_coef * torch.stack(entropies).sum()
        loss         = policy_loss + entropy_loss

        optimizer.zero_grad()
        loss.backward()
        nn.utils.clip_grad_norm_(policy.parameters(), max_norm=2.0)
        optimizer.step()

        ep_reward = sum(rewards)
        reward_log.append(ep_reward)

        if ep % 20 == 0:
            window = reward_log[-20:]
            avg    = sum(window) / len(window)
            print(
                f"Episode {ep:4d} | Reward: {ep_reward:+.3f} | "
                f"20-ep avg: {avg:+.3f} | Baseline: {baseline:+.3f} | "
                f"Revisions: {env.revisions}"
            )

    return reward_log

@torch.no_grad()
def evaluate(dataset, policy: PolicyNet, n: int = 50) -> dict:
    policy.eval()
    env = SelfCorrectionEnv(dataset, max_revisions=3)

    results      = {"zero_shot": 0, "always_revise": 0, "rl_policy": 0}
    total_reward = {"rl_policy": 0.0}
    samples      = random.sample(list(dataset), n)

    for sample in samples:
        question = sample["question"]
        solution = sample["answer"]
        true_ans = extract_gsm8k_answer(solution)
        #zero shot
        ans0 = call_llm(question)
        if answers_match(extract_number(ans0), true_ans):
            results["zero_shot"] += 1

        # always revise
        ans = ans0
        for _ in range(3):
            ans = call_llm(question, ans)
        if answers_match(extract_number(ans), true_ans):
            results["always_revise"] += 1

        # RL policy
        env.question  = question
        env.solution  = solution
        env.true_ans  = true_ans
        env.answer    = ans0
        env.revisions = 0
        state         = env._get_state()
        done          = False
        ep_reward     = 0.0

        while not done:
            probs  = policy(state.to(device))
            action = probs.argmax().item()
            state, reward, done = env.step(action)
            ep_reward += reward

        if answers_match(extract_number(env.answer), true_ans):
            results["rl_policy"] += 1
        total_reward["rl_policy"] += ep_reward

    pct = {k: v / n * 100 for k, v in results.items()}
    avg_rl_reward = total_reward["rl_policy"] / n

    for k, v in pct.items():
        print(f"  {k:<20s}: {v:.1f}%  ({results[k]}/{n})")
    print(f"\n  RL Policy avg episode reward : {avg_rl_reward:+.4f}")
    return pct

if __name__ == "__main__":
    env       = SelfCorrectionEnv(dataset, max_revisions=3)
    input_dim = env.reset().shape[0]   # EMBED_DIM + 1
    print(f"State dim: {input_dim}")

    policy = PolicyNet(input_dim).to(device)

    reward_log = train(env, policy, episodes=600)
    torch.save(policy.state_dict(), "policy.pt")
    evaluate(dataset_test, policy, n=50)